# Github Action to create a release with goreleaser
name: Create Release

on:
  push:
    branches:
      - 'master'
    paths:
      - version.txt

jobs:
  release:
    if: ${{ github.repository == 'kubernetes-sigs/aws-iam-authenticator' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.RELEASE_KEY }}"

      - name: Tag release
        run: |
          /usr/bin/git config --global user.email actions@github.com
          /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
          hack/tag-release.sh

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
